# my-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: similarity-service-deployment
  labels:
    app: similarity-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: similarity-service
  template:
    metadata:
      labels:
        app: similarity-service
    spec:
      containers:
      - name: model-container
        image: my-grpc-milvus-app:latest
        ports:
        - containerPort: 50051  # the container's listening port
        # If you need environment variables, add them here
        # env:
        #   - name: MILVUS-HOST
        #     value: "milvus"
        #   - name: MILVUS-PORT
        #     value: "19530"
