# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/Analyzer.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'proto/Analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/Analyzer.proto\x12\x08\x41nalyser\"\x14\n\x05Image\x12\x0b\n\x03url\x18\x01 \x01(\t\"D\n\x0e\x41nalyzeRequest\x12#\n\nbase_image\x18\x01 \x01(\x0b\x32\x0f.Analyser.Image\x12\r\n\x05model\x18\x02 \x01(\t\"M\n\x0f\x41nalyzeResponse\x12\x0b\n\x03\x61ge\x18\x01 \x01(\t\x12\x0e\n\x06gender\x18\x02 \x01(\t\x12\x0f\n\x07\x65motion\x18\x03 \x01(\t\x12\x0c\n\x04race\x18\x04 \x01(\t2L\n\x08\x41nalyser\x12@\n\x07\x41nalyze\x12\x18.Analyser.AnalyzeRequest\x1a\x19.Analyser.AnalyzeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.Analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGE']._serialized_start=34
  _globals['_IMAGE']._serialized_end=54
  _globals['_ANALYZEREQUEST']._serialized_start=56
  _globals['_ANALYZEREQUEST']._serialized_end=124
  _globals['_ANALYZERESPONSE']._serialized_start=126
  _globals['_ANALYZERESPONSE']._serialized_end=203
  _globals['_ANALYSER']._serialized_start=205
  _globals['_ANALYSER']._serialized_end=281
# @@protoc_insertion_point(module_scope)
