# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/ImageService.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'proto/ImageService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/ImageService.proto\x12\x0cImageService\"\x14\n\x05Image\x12\x0b\n\x03url\x18\x01 \x01(\t\":\n\x0fIdentifyRequest\x12\'\n\nbase_image\x18\x01 \x01(\x0b\x32\x13.ImageService.Image\"B\n\x10IdentifyResponse\x12.\n\x11\x63omparison_images\x18\x01 \x03(\x0b\x32\x13.ImageService.Image2[\n\x0cImageService\x12K\n\x08Identify\x12\x1d.ImageService.IdentifyRequest\x1a\x1e.ImageService.IdentifyResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ImageService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGE']._serialized_start=42
  _globals['_IMAGE']._serialized_end=62
  _globals['_IDENTIFYREQUEST']._serialized_start=64
  _globals['_IDENTIFYREQUEST']._serialized_end=122
  _globals['_IDENTIFYRESPONSE']._serialized_start=124
  _globals['_IDENTIFYRESPONSE']._serialized_end=190
  _globals['_IMAGESERVICE']._serialized_start=192
  _globals['_IMAGESERVICE']._serialized_end=283
# @@protoc_insertion_point(module_scope)
