# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/Preprocessor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/Preprocessor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/Preprocessor.proto\x12\x0cPreprocessor\"\x14\n\x05Image\x12\x0b\n\x03url\x18\x01 \x01(\t\"<\n\x11PreprocessRequest\x12\'\n\nbase_image\x18\x01 \x01(\x0b\x32\x13.Preprocessor.Image\"d\n\x12PreprocessResponse\x12,\n\x0fprocessed_image\x18\x01 \x01(\x0b\x32\x13.Preprocessor.Image\x12\x0f\n\x07scale_w\x18\x02 \x01(\x05\x12\x0f\n\x07scale_h\x18\x03 \x01(\x05\x32\x61\n\x0cPreprocessor\x12Q\n\nPreprocess\x12\x1f.Preprocessor.PreprocessRequest\x1a .Preprocessor.PreprocessResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.Preprocessor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGE']._serialized_start=42
  _globals['_IMAGE']._serialized_end=62
  _globals['_PREPROCESSREQUEST']._serialized_start=64
  _globals['_PREPROCESSREQUEST']._serialized_end=124
  _globals['_PREPROCESSRESPONSE']._serialized_start=126
  _globals['_PREPROCESSRESPONSE']._serialized_end=226
  _globals['_PREPROCESSOR']._serialized_start=228
  _globals['_PREPROCESSOR']._serialized_end=325
# @@protoc_insertion_point(module_scope)
