# my-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyzer-service-deployment
  labels:
    app: analyzer-service
spec:
  replicas: 4
  selector:
    matchLabels:
      app: analyzer-service
  template:
    metadata:
      labels:
        app: analyzer-service
    spec:
      sessionAffinity: None
      nodeSelector:
        role: analyzer
      containers:
      - name: model-container
        imagePullPolicy: Always
        image: pomidoro/similarity-service:1
        ports:
        - containerPort: 50051  # the container's listening port
        envFrom:
          - configMapRef:
              name: analyzer-service-config
